### ISSUE TITLE
crashes after last update

### ISSUE THREAD

**Issue by Liimp** [atareao/my-weather-indicator#101]
After last update:
/opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator
Traceback (most recent call last):
  File "/opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator", line 35, in <module>
    from myweatherindicator import main
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 51, in <module>
    import preferences
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/preferences.py", line 38, in <module>
    import mipaddress
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/mipaddress.py", line 87
    if ans and (data := re.compile(r'(\d+\.\d+\.\d+\.\d+)').search(ans)):
                     ^
SyntaxError: invalid syntax

Ubuntu 18.04
:(

**Comment by atareao** [comment]
Fixed in my-weather-indicator - 0.10.1-0extras23.04.00

**Comment by Liimp** [comment]
Didn't fix for me :(

**Comment by atareao** [comment]
I fix this 🪲... 🙏 Thanks for your help

**Comment by atareao** [comment]
Fixed on  my-weather-indicator - 0.10.2-0extras23.04.00
