### ISSUE TITLE
issue don´t fix

### ISSUE THREAD

**Issue by DocHifi** [atareao/my-weather-indicator#119]
Referring to the closed issue here:
https://github.com/atareao/my-weather-indicator/issues/107#issuecomment-1513621686
Im sorry to tell you, that it is not fixed.
There is another user ([naveen1100] with the same issue.
Can yo please have a look and try to fix it.
Ubuntu Mate 20.04-6 and my-weather-indicator  0.10.5-0extras23.04.00 all .
I love your program and want to use it, but in this state it is useless.
If it helps. when I start in Terminal and search for my location I get this output:
```
Traceback (most recent call last):
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/whereami.py", line 184, in ontreeviewcursorchanged
    self.set_position(model[aiter][3], model[aiter][4])
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/whereami.py", line 295, in set_position
    self.web_send(f"setPosition({self._latitude}, {self._longitude});")
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/whereami.py", line 316, in web_send
    self.viewer.evaluate_javascript(msg, len(msg), None, "localhost", None)
AttributeError: 'WebView' object has no attribute 'evaluate_javascript'
```
After this I can´t click OK or Cancel, the only way to close the window is the x in the upper right corner.

**Comment by atareao** [comment]
Thanks @DocHifi . Fixed in my-weather-indicator - 0.10.11-0extras23.04.00
