### ISSUE TITLE
Crashes when running from startup applications

### ISSUE THREAD

**Issue by svartkanin** [atareao/my-weather-indicator#21]
I'm running Linux k6174 4.4.0-36-generic #55-Ubuntu SMP Thu Aug 11 18:01:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux.
I put the indicator into the startup applications, but it never started automatically. By looking into the /var/log/syslog I detected that it crashes every time with the following stacktrace:

Traceback (most recent call last):
File "/opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator", line 69, in <module>
     mwi = MWI()
   File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 143, in **init**
     self.load_preferences()
   File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 369, in load_preferences
     self.update_weather()
   File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 158, in update_weather
     self.update_menu(i)
   File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 642, in update_menu
     location = geocodeapi.get_inv_direction(lat, lon)['city']
   File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/geocodeapi.py", line 132, in get_inv_direction
     aplace = reverse.resolve()
 GLib.Error: geocode_error: Unable to geocode (1)

I tried to debug it and saw that the passed parameters for longitude and latitude in the function `def get_inv_direction` are both 0!
Apparently the previous filling of those values in the ipaddress module via `def get_current_location()` does not work since the `GetPosition` returns 0 there!?

I was also wondering if 0 is returned why the values in the config file $HOME/.config/my-weather-indicator/my-weather-indicator.conf are not choosen?

Let me know if you need more infos

Cheers

**Comment by ansonjacob-aj** [comment]
I am also facing this issue

**Comment by valkirilov** [comment]
+1

**Comment by snex** [comment]
+1, if you set "first-time" to false in config, you can run the app and set your location manually.

**Comment by atareao** [comment]
Fixed in last version
