### ISSUE TITLE
Error in startup

### ISSUE THREAD

**Issue by snex** [atareao/my-weather-indicator#50]
```
<gettext.GNUTranslations` object at 0x7f6589f8d828>
#####################################################
System: Linux
Machine: x86_64
Node: snex-desktop
Release: 4.15.0-35-generic
Version: #38-Ubuntu SMP Wed Sep 12 10:38:24 UTC 2018
Platform: Linux-4.15.0-35-generic-x86_64-with-Ubuntu-18.04-bionic
My-Weather-Indicator version: 0.9.0-0extras17.10.4
#####################################################

****** Requesting timezone identificacion
** OWM **
4887398 -87.6198 41.8632
1
***** refreshing weather *****
OK. Internet connection. HTTPConnection: www.google.com
--- Updating data in location 0 ---
http://geoip.nekudo.com/api/
HTTPSConnectionPool(host='geoip.nekudo.com', port=443): Max retries exceeded with url: /shutdown (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.",))
Traceback (most recent call last):
  File "/opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator", line 62, in <module>
    mwi = MWI()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 141, in __init__
    self.load_preferences()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 366, in load_preferences
    self.update_weather()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 156, in update_weather
    self.update_menu(i)
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 638, in update_menu
    lat, lon = ipaddress.get_current_location()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/ipaddress.py", line 114, in get_current_location
    ans = json.loads(comun.read_from_url(url))
  File "/usr/lib/python3.6/json/__init__.py", line 348, in loads
    'not {!r}'.format(s.__class__.__name__))
```

The URL referred to in ipaddress.py, "https://geoip.nekudo.com/api", seems to be deprecated.

**Comment by amilino** [comment]
Yes, I have the same issue. Please help and push it to ppa:atareao/atareao if possible. :)

**Comment by atareao** [comment]
Fixed
