### ISSUE TITLE
Failure on fresh Ubuntu 20.04

### ISSUE THREAD

**Issue by dvarrazzo** [atareao/my-weather-indicator#75]
On a relatively fresh Ubuntu 20.04 installation the app fails to work. This is the traceback from command line. What dependecny package might be missing?

```
piro@goya:~$ /opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator 
<gettext.GNUTranslations object at 0x7fa02ce1a100>
#####################################################
System: Linux
Machine: x86_64
Node: goya
Release: 5.4.0-42-generic
Version: #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020
Platform: Linux-5.4.0-42-generic-x86_64-with-glibc2.29
My-Weather-Indicator version: 0.9.4-0extras19.10.09
#####################################################

My-Weather-Indicator version: 0.9.4-0extras19.10.09
#####################################################
****** Requesting timezone identificacion
** OWM **
2643743 -0.1276474 51.5073219
1
***** refreshing weather *****
OK. Internet connection. HTTPConnection: www.google.com
--- Updating data in location 0 ---
****** Updating weather
****** Calculating rawOffset
-------------------------------------------------------
OpenWeatherMap Weather Service url:http://api.openweathermap.org/data/2.5/weather?id=2643743&appid=4516154e5c8a6494e7e13b550408c863
-------------------------------------------------------
****** Updated weather
None
Traceback (most recent call last):
  File "/opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator", line 36, in <module>
    main()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 953, in main
    mwi = MWI()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 124, in __init__
    self.load_preferences()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 349, in load_preferences
    self.update_weather()
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 139, in update_weather
    self.update_menu(i)
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 804, in update_menu
    self.notifications[index].show()
gi.repository.GLib.Error: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files (2)
```

**Comment by dvarrazzo** [comment]
Note: my window manager is i3, so it might be missing something that the stock Gnome provides by default.

**Comment by SolarAquarion** [comment]
I get that problem too, but different

Traceback (most recent call last):
  File "/usr/bin/my-weather-indicator", line 36, in <module>
    main()
  File "/usr/share/my-weather-indicator/myweatherindicator.py", line 953, in main
    mwi = MWI()
  File "/usr/share/my-weather-indicator/myweatherindicator.py", line 124, in __init__
    self.load_preferences()
  File "/usr/share/my-weather-indicator/myweatherindicator.py", line 349, in load_preferences
    self.update_weather()
  File "/usr/share/my-weather-indicator/myweatherindicator.py", line 139, in update_weather
    self.update_menu(i)
  File "/usr/share/my-weather-indicator/myweatherindicator.py", line 804, in update_menu
    self.notifications[index].show()
gi.repository.GLib.Error: g-io-error-quark: Error calling StartServiceByName for org.freedesktop.Notifications: Timeout was reached (24)

**Comment by carminefa** [comment]
fixed https://bugs.launchpad.net/my-weather-indicator/+bug/1121999

(Seems like the Open Weather API has slightly changed; in particular, "snow codes" with ID=6xx are extended, while my-weather-indicator does not know about new codes. I made a quick patch by taking new codes from there: https://openweathermap.org/weather-conditions#Weather-Condition-Codes-2.

Basically,, you need to patch (see attached)
${INSTALL_ROOT}/my-weather-indicator/share/my-weather-indicator/wopenweathermapapi.py)

**Comment by carminefa** [comment]
download the patch

https://bugs.launchpad.net/my-weather-indicator/+bug/1121999/+attachment/5442410/+files/wopenweathermapapi.py.patch

in this path:

/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator

and then run the command to patch:

sudo patch -u -b wopenweathermapapi.py -i wopenweathermapapi.py.patch

then launch:

/opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator

thanks ileyka
