### ISSUE TITLE
some locations in Germany not working

### ISSUE THREAD

**Issue by OneTwoBarbecue** [atareao/my-weather-indicator#83]
Hi, 
since a few days my-weather-indicator is unable to get the previously working weather-informations for various German locations.

For example "Freiburg im Breisgau" is not working with OpenWeatherMap

Error shown is:

```
Traceback (most recent call last):

File "/opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator", line 36, in <module>
main()

File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 956, in main
   MWI()

File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 126, in __init__
self.load_preferences()

File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 352, in load_preferences
self.update_weather()

File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 141, in update_weather
self.update_menu(i)

File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 669, in update_menu
weather = self.weatherservices[index].get_weather()

File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/wopenweathermapapi.py", line 263, in get_weather
condition = CONDITION[data['weather'][0]['id']]
KeyError: 616
```
Regards, 
  Marco

**Comment by erichlf** [comment]
This is a duplicate of #81 and is caused by new keys added by open weather.

**Comment by val-kulkov** [comment]
@OneTwoBarbecue : while we are waiting @atareao 's response, you can simply [download the revised version](https://raw.githubusercontent.com/atareao/my-weather-indicator/4bfc87d6d778f27078c2ed3f061d26ab5051eb12/src/wopenweathermapapi.py) of wopenweathermapapi.py from #82 and replace your file with the one you downloaded.

**Comment by OneTwoBarbecue** [comment]
Great! Thank you very much @val-kulkov!
