### ISSUE TITLE
Ubuntu 22.04.1 LTS problem SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by tommyNy** [atareao/my-weather-indicator#96]
After Ubuntu distro upgraded to 22.04.1 LTS and Python 3.10.4

user@laptop:~$ /opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator 
<gettext.GNUTranslations object at 0x7f595d720580>
Traceback (most recent call last):
  File "/opt/extras.ubuntu.com/my-weather-indicator/bin/my-weather-indicator", line 59, in <module>
    from myweatherindicator import MWI
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/myweatherindicator.py", line 49, in <module>
    import preferences
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/preferences.py", line 33, in <module>
    from whereami import WhereAmI
  File "/opt/extras.ubuntu.com/my-weather-indicator/share/my-weather-indicator/whereami.py", line 34
    from async import async_function
         ^^^^^
SyntaxError: invalid syntax

**Comment by atareao** [comment]
Fixed in last update
